sylius_resource:
    resources:
        vs_cms.pages:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Cms\Page
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: IA\CmsBundle\Controller\PagesController
                repository: IA\CmsBundle\Entity\Repository\PagesRepository
                form:       IA\CmsBundle\Form\PageForm
        vs_cms.page_categories:
            driver: doctrine/orm
            classes:
                model:      App\Entity\Cms\PageCategory
                interface:  Sylius\Component\Resource\Model\ResourceInterface
                controller: IA\CmsBundle\Controller\PagesController
                repository: IA\CmsBundle\Entity\Repository\PageCategoryRepository
                