parameters:
#    ia_users.example.class: VS\UsersBundle\Example

services:
    ia_users.form.type.users:
        class: VS\UsersBundle\Form\UserCrudFormType
        tags:
            - { name: form.type, alias: 'ia_users_users' }
        arguments: ['@doctrine']
        
    ia_users.form.type.registration:
        class: VS\UsersBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: ia_user_registration }
    ia_user.registration_listener:
        class: VS\UsersBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
    ia_user.password_resetting:
        class: VS\UsersBundle\EventListener\PasswordResettingListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
