imports:
    - { resource: services/form.yaml }

parameters:
#    ia_cms.example.class: IACmsBundle\Example

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
