imports:
    - { resource: services/form.yaml }

parameters:
#    ia_cms.example.class: IACmsBundle\Example

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ia_cms.form.type.pages:
        class: IA\CmsBundle\Form\PageForm
        tags:
            - { name: form.type, alias: 'ia_cms_pages' }
        arguments: ['@doctrine']
        
    ###########################################################
    # Menu services
    ###########################################################
    app.menu_builder:
        class: IA\CmsBundle\Component\Menu\MenuBuilder
        arguments: ["%menu.config_file%", "@security.authorization_checker", "@router"]
        calls:
          - [ setContainer ]

    app.main_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", mainMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: main }
            
    app.profile_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", profileMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: profile }
    
    app.breadcrumbs_menu:
        autowire: false
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", breadcrumbsMenu]
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu, alias: breadcrumbs }

    ###########################################################
    # Taxonomy services
    ###########################################################
    ia_cms.form.type.taxonomy_vocabulary:
        class: IACmsBundle\Form\TaxonomyVocabularyForm
        tags:
            - { name: form.type, alias: 'ia_cms_taxonomy_vocabularies' }
        arguments: ['@doctrine']
        
    ia_cms.form.type.taxonomy_term:
        class: IACmsBundle\Form\TaxonomyTermForm
        tags:
            - { name: form.type, alias: 'ia_cms_taxonomy_terms' }
        arguments: ['@doctrine']
