services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Vankosoft\ApplicationBundle\Controller\ApiTestController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.repository.application'


