services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.context.application.hostname_based_request_resolver:
        class: Vankosoft\ApplicationBundle\Component\Context\HostnameBasedRequestResolver
        arguments:
            - '@vs_application.repository.application'
        tags:
            - { name: 'vs_application.context.application.request_based_resolver' }

    vs_application.context.application:
        class: Vankosoft\ApplicationBundle\Component\Context\ApplicationContext
        arguments:
            - '@vs_application.context.application.hostname_based_request_resolver'
            - '@request_stack'
        tags:
            - { name: 'vs_application.context.application' }
    
    # Create Aliases for Autowiring
    Vankosoft\ApplicationBundle\Component\Context\ApplicationContext: '@vs_application.context.application'
    Vankosoft\ApplicationBundle\Component\Context\ApplicationContextInterface: '@Vankosoft\ApplicationBundle\Component\Context\ApplicationContext'

    vs_application.exception_listener:
        class: Vankosoft\ApplicationBundle\EventListener\ExceptionListener
        arguments:
            - '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    
    vs_application.slug_generator:
        class: Vankosoft\ApplicationBundle\Component\SlugGenerator
        arguments:
            - '@request_stack'
            
    #################################################################
    # Subscribe to Application Resources Events
    #################################################################
    vs_application.resource_listener:
        class: Vankosoft\ApplicationBundle\EventSubscriber\ApplicationResourceListener
        arguments:
            - '@sylius.resource_registry'
            - '@vs_users.factory.user_activity'
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags:
            #- { name: 'doctrine.event_subscriber', event: 'kernel.request', method: 'onKernelRequest' }
            - { name: 'doctrine.event_subscriber', priority: 9000 }
