services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.context.application.hostname_based_request_resolver:
        class: Vankosoft\ApplicationBundle\Component\Context\HostnameBasedRequestResolver
        arguments:
            - '@vs_application.repository.application'
        tags:
            - { name: 'vs_application.context.application.request_based_resolver' }

    vs_application.context.application:
        class: Vankosoft\ApplicationBundle\Component\Context\ApplicationContext
        arguments:
            - '@vs_application.context.application.hostname_based_request_resolver'
            - '@request_stack'
        tags:
            - { name: 'vs_application.context.application' }

