services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_app.command.maintenance:
        class: Vankosoft\ApplicationBundle\Command\MaintenanceModeCommand
        tags:
            - 'console.command'
