services:
    vs_cms.form.type.pages:
        class: IA\CmsBundle\Form\PageForm
        tags:
            - { name: form.type }
        arguments: ['%vs_cms.model.pages.class%', $categoryClass: '%vs_cms.model.page_categories.class%']   # '%ia_cms.pages.form.type.validation_groups%'
        