services:
    vs_application.resources.application.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\ApplicationForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.application.class%']

    vs_application.resources.settings.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\SettingsForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.settings.class%', '%vs_cms.model.pages.class%']

    vs_application.resources.taxonomy.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\TaxonomyForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.taxonomy.class%']
        
    vs_application.resources.taxon.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\TaxonForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.taxon.class%']
        
    vs_application.resources.locale.form:
        public: true
        class: Vankosoft\ApplicationBundle\Form\LocaleForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.locale.class%']
