services:
    vs_application.resources.settings.form:
        public: true
        class: VS\ApplicationBundle\Form\GeneralSettingsForm
        tags:
            - { name: form.type }
        arguments: ['%vs_application.model.settings.class%', '%vs_cms.model.pages.class%']
        