parameters:
    vs_application.in_maintenance: false
services:
    vs_app.twig.alerts:
        class: VS\ApplicationBundle\Twig\Alerts
    
    vs_app.listener.maintenance:
        class: VS\ApplicationBundle\EventListener\MaintenanceListener
        arguments: 
            - '@service_container'
            - '%vs_application.settings.application_id%'
            - '%vs_application.settings.application_layout%'
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }