services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
            
    vs_application.resource_action_subscriber:
        class: Vankosoft\ApplicationBundle\EventListener\ResourceAction\ResourceActionSubscriber
        arguments:
            - '@vs_users.factory.user_activity'
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags: [kernel.event_subscriber]


