services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.widgets_builder:
        class: Vankosoft\ApplicationBundle\Component\Widget\WidgetBuilder
        arguments:
            - '@security.token_storage'
            - '@vs_application.repository.widget'
    
    Vankosoft\ApplicationBundle\Controller\WidgetExtController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@cache.app'
            - '@doctrine'
            - '@vs_application.repository.widget'
            - '@vs_application.factory.widget'
            
    # Load Widgets
    Vankosoft\ApplicationBundle\EventListener\Widgets\LocalesWidget:
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }