services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    vs_app.command.maintenance:
        class: Vankosoft\ApplicationBundle\Command\MaintenanceModeCommand
        tags:
            - 'console.command'

    vs_app.command.regenerate_slugs:
        class: Vankosoft\ApplicationBundle\Command\RegenerateSlugsCommand
        tags:
            - 'console.command'
