parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    vs_application.project_issues:
        class: Vankosoft\ApplicationBundle\Component\Application\ProjectIssue
        arguments:
            - '@http_client'
            - '@vs_application.doctrine_dbal_cache'
    
    Vankosoft\ApplicationBundle\Controller\VankosoftIssueController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_application.project_issues'


