services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        
    Pd\WidgetBundle\Controller\WidgetController:
        tags: ['controller.service_arguments']
        autowire: true
        calls:
            - [ setContainer, [ '@service_container' ] ]
    
    # Load All Widgets
#     Vankosoft\ApplicationBundle\Widgets\:
#         resource: '../src/Widgets/*'
#         tags:
#             - { name: kernel.event_listener, event: widget.start, method: builder }
            
    # Load Single Widget
    Vankosoft\ApplicationBundle\Widgets\LocalesWidget:
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }