parameters:
    vs_application.widgets.base_template: '@VSApplication/Widgets/widgetBase.html.twig'
    vs_application.widgets.return_route: 'app_home'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    ###################################################################
    # Widgets Builder Services
    ###################################################################
    vs_application.widgets_builder:
        class: Vankosoft\ApplicationBundle\Component\Widget\WidgetBuilder
        arguments:
            - '@security.token_storage'
            - '@vs_application.repository.widget'
            - '@vs_application.repository.widget_config'
            
    vs_application.widgets_container:
        class: Vankosoft\ApplicationBundle\Component\Widget\Widget
        arguments:
            - '@security.helper'
            - '@event_dispatcher'
            - '@cache.app'
            - '@security.token_storage'
            - '@doctrine'
            - '@vs_application.repository.widget_config'
            - '@vs_application.factory.widget_config'
            
    vs_application.twig_widget_renderer:
        class: Vankosoft\ApplicationBundle\Twig\Renderer\WidgetRenderer
        arguments:
            - '@twig'
            - '@cache.app'
            - '@security.token_storage'
            - '%vs_application.widgets.base_template%'
    
    Vankosoft\ApplicationBundle\Twig\WidgetExtension:
        tags: ['twig.extension']
        arguments:
            - '@vs_application.twig_widget_renderer'
            - '@vs_application.widgets_builder'
            - '@vs_application.widgets_container'
        
    Vankosoft\ApplicationBundle\Controller\WidgetsConfigsController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@cache.app'
            - '@doctrine'
            - '@vs_application.widgets_container'
            - '@vs_application.repository.widget_config'
            - '@vs_application.factory.widget_config'
            
    ###################################################################
    # Load Widgets
    ###################################################################
    Vankosoft\ApplicationBundle\EventListener\Widgets\UserInfoWidget:
        arguments:
            - '@vs_application.repository.widget'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }
    
    Vankosoft\ApplicationBundle\EventListener\Widgets\LocalesMenuWidget:
        arguments:
            - '@vs_application.repository.widget'
            - '@vs_application.repository.locale'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }
            
    Vankosoft\ApplicationBundle\EventListener\Widgets\ApplicationsMenuWidget:
        arguments:
            - '@vs_application.repository.widget'
            - '@vs_application.repository.application'
        tags:
            - { name: kernel.event_listener, event: widget.start, method: builder }


