
ia_cms_pages:
    resource: |
        alias: ia_cms.pages
        path: /pages
        templates: "@IACms/Pages"
    type: sylius.resource

ia_cms_page_categories_index:
    path: /pages/categories
    controller: App\Controller\Admin\PagesCategoryController::index
ia_cms_page_categories_create:
    path: /pages/categories/new
    controller: App\Controller\Admin\PagesCategoryController::create
ia_cms_page_categories_update:
    path: /pages/categories/{id}/edit
    controller: App\Controller\Admin\PagesCategoryController::update
