
ia_cms_pages:
    resource: |
        alias: ia_cms.pages
        path: /pages
        templates: "@IACms/Pages"
    type: sylius.resource

ia_cms_page_categories_index:
    path: /page_categories
    controller: IA\CmsBundle\Controller\PagesCategoryController::index
ia_cms_page_categories_create:
    path: /page_categories/new
    controller: IA\CmsBundle\Controller\PagesCategoryController::create
ia_cms_page_categories_update:
    path: /page_categories/{id}/edit
    controller: IA\CmsBundle\Controller\PagesCategoryController::update
