vs_app_settings:
    resource: |
        alias: vs_application.settings
        path: /settings
        templates: "@VSApplication/Settings"
    type: sylius.resource

vs_app_settings_handle:
    path: /settings-handle/{siteId}
    controller: VS\ApplicationBundle\Controller\SettingsExtController::handle
