vs_application_settings:
    resource: |
        alias: vs_application.settings
        path: /settings
        templates: "@VSApplication/Pages/Settings"
    type: sylius.resource

vs_application_application_form:
    path: /application-edit/form-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::index
    
vs_application_application_handle:
    path: /application-edit/handle-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::handle
    
vs_application_application_remove:
    path: /application-edit/remove-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\ApplicationExtController::remove

vs_application_settings_form:
    path: /settings-edit/form-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\SettingsExtController::index

vs_application_settings_handle:
    path: /settings-edit/handle-{applicationId}
    controller: Vankosoft\ApplicationBundle\Controller\SettingsExtController::handle


vs_application_locales:
    resource: |
        alias: vs_application.locale
        except: ['show']
        path: /locales
        templates: "@VSApplication/Pages/Locales"
    type: sylius.resource
