vs_app_taxonomy:
    resource: |
        alias: vs_application.taxonomy
        path: /taxonomy
        templates: "@VSApplication/Taxonomy"
    type: sylius.resource

vs_application_taxon:
    path: /taxonomy/taxons
    controller: VS\ApplicationBundle\Controller\TaxonController::index
