vs_app_taxonomy:
    path: /taxonomy/index
    controller: VS\ApplicationBundle\Controller\TaxonomyController::index

vs_app_taxon:
    path: /taxonomy/taxons
    controller: VS\ApplicationBundle\Controller\TaxonController::index
