vs_application_widget_ext_index:
    path: /widget-ext/listing
    controller:  Vankosoft\ApplicationBundle\Controller\WidgetExtController::index

vs_application_widget_ext_status:
    path: /widget-ext/status/{widgetId}/{status}
    controller:  Vankosoft\ApplicationBundle\Controller\WidgetExtController::status
    requirements:
        status: \d+

vs_application_widget_ext_config:
    path: /widget-ext/config/{widgetId}
    controller:  Vankosoft\ApplicationBundle\Controller\WidgetExtController::configs

vs_application_widget_ext_order:
    path: /widget-ext/order/{widgetId}/{order}
    controller:  Vankosoft\ApplicationBundle\Controller\WidgetExtController::order
    requirements:
        order: \d+
