imports:
    - { resource: services/application.yaml }
    - { resource: services/controller.yaml }
    - { resource: services/settings.yaml }
    - { resource: services/form.yaml }
    - { resource: services/maintenance.yaml }
    - { resource: services/theme.yaml }
    - { resource: services/menu.yaml }
    - { resource: services/i18n.yaml }
    - { resource: services/doctrine_extensions.yaml }
    - { resource: services/commands.yaml }
    - { resource: services/web_profiler.yaml }
    - { resource: services/repository.yaml }
    - { resource: services/api.yaml }
    - { resource: services/twig.yaml }

parameters:
    vs_application.version: !php/const Vankosoft\ApplicationBundle\Component\Application\Kernel::VERSION
    vs_application.public_dir: "%kernel.project_dir%/public/admin-panel"
    vs_application.settings.application_id: null
    vs_application.settings.application_layout: null
    vs_application.supress_pdo_exception: false
    vs_application.page_categories.taxonomy_code: 'page-categories'
    vs_application.document_categories.taxonomy_code: 'document-categories'
    vs_application.user_roles.taxonomy_code: 'user-roles'
    vs_application.mailer_user: 'webmaster@vankosoft.org'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

